name: Deploy GitHub Pages 
on: 
  push: 
    branches: 
      - main 
  
 
 
jobs: 
  deploy: 
    runs-on: ubuntu-latest 
    steps: 
      - name: Checkout Code 
        uses: actions/checkout@v3 
  
      - name: Set up SSH Key 
        uses: webfactory/ssh-agent@v0.5.3 
        with: 
          ssh-private-key: ${{ secrets.ACTIONS_DEPLOY_SSH_KEY }} 
  
      - name: Deploy to GitHub Pages 
        uses: peaceiris/actions-gh-pages@v3 
        with: 
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_SSH_KEY }} 
          publish_dir: . 
          publish_branch: gh-pages 
